---
- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
  - name: Editing parameteres on /etc/sysctl.conf" in order to improve network performance
    shell: |
      sed -i "/^net/d" /etc/sysctl.conf
      echo -e 'net.core.wmem_max = 20971520' >> /etc/sysctl.conf
      echo -e 'net.core.rmem_max = 20971520' >> /etc/sysctl.conf
      echo -e 'net.ipv4.tcp_rmem = 5242880 10485760 109715200' >> /etc/sysctl.conf
      echo -e 'net.ipv4.tcp_wmem = 5242880 10485760 109715200' >> /etc/sysctl.conf
      echo -e 'net.ipv4.tcp_window_scaling = 1' >> /etc/sysctl.conf
      echo -e 'net.ipv4.tcp_timestamps = 0' >> /etc/sysctl.conf
      echo -e 'net.ipv4.tcp_sack = 0' >> /etc/sysctl.conf
      echo -e 'net.ipv4.tcp_dsack = 0' >> /etc/sysctl.conf
      echo -e 'net.ipv4.tcp_no_metrics_save = 1' >> /etc/sysctl.conf
      echo -e 'net.core.netdev_max_backlog = 15000' >> /etc/sysctl.conf

  - name: Applying all sysctl changes
    shell:
      sysctl --system